// Generated by CoffeeScript 1.6.1
(function() {

  $(function() {
    var canvas, ctx, hasGetUserMedia, render, video;
    hasGetUserMedia = function() {
      return !!(navigator.getUserMedia || navigator.webkitGetUserMedia || navigator.mozGetUserMedia || navigator.msGetUserMedia);
    };
    video = $('#video')[0];
    canvas = $('#canvas')[0];
    ctx = canvas.getContext('2d');
    navigator.getUserMedia = navigator.webkitGetUserMedia || navigator.getUserMedia;
    window.URL = window.URL || window.webkitURL;
    if (hasGetUserMedia()) {
      console.log('カメラOk');
    } else {
      alert('カメラが使用できません');
    }
    navigator.getUserMedia({
      video: true
    }, function(stream) {
      var localMediaStream;
      localMediaStream = stream;
      video.src = window.URL.createObjectURL(localMediaStream);
      video.play();
      return setInterval(render, 100);
    }, function(err) {
      alert('error');
      return console.log(err);
    });
    return render = function() {
      console.log('rendered');
      canvas.height = video.videoHeight;
      canvas.width = video.videoWidth;
      return ctx.drawImage(video, 0, 0);
    };
  });

}).call(this);
